In [1]:
import numpy as np

<img src="racingcar1.jpeg"/>

In [7]:
# Converting image into numpy array

In [8]:
from matplotlib.image import imread

In [9]:
car=imread("racingcar1.jpeg")

In [10]:
type(car)

numpy.ndarray

In [11]:
car

array([[[228, 238, 247],
        [228, 238, 247],
        [228, 239, 245],
        ...,
        [ 52,  68,   5],
        [ 56,  71,   6],
        [ 63,  75,   9]],

       [[228, 238, 247],
        [228, 239, 245],
        [228, 239, 245],
        ...,
        [ 46,  63,   8],
        [ 57,  72,  15],
        [ 67,  81,  22]],

       [[228, 239, 245],
        [228, 239, 245],
        [228, 239, 245],
        ...,
        [ 39,  61,  15],
        [ 55,  72,  27],
        [ 65,  81,  34]],

       ...,

       [[146, 144, 132],
        [148, 146, 134],
        [150, 148, 136],
        ...,
        [144, 144, 136],
        [143, 143, 135],
        [142, 142, 134]],

       [[146, 142, 131],
        [147, 143, 132],
        [148, 144, 133],
        ...,
        [143, 143, 135],
        [141, 141, 133],
        [138, 138, 130]],

       [[145, 141, 130],
        [145, 141, 130],
        [145, 141, 130],
        ...,
        [152, 152, 144],
        [148, 148, 140],
        [145, 145, 137]]

In [12]:
car.size

499500

In [13]:
car.shape

(333, 500, 3)

In [14]:
car.ndim

3

In [15]:
car[:101]

array([[[228, 238, 247],
        [228, 238, 247],
        [228, 239, 245],
        ...,
        [ 52,  68,   5],
        [ 56,  71,   6],
        [ 63,  75,   9]],

       [[228, 238, 247],
        [228, 239, 245],
        [228, 239, 245],
        ...,
        [ 46,  63,   8],
        [ 57,  72,  15],
        [ 67,  81,  22]],

       [[228, 239, 245],
        [228, 239, 245],
        [228, 239, 245],
        ...,
        [ 39,  61,  15],
        [ 55,  72,  27],
        [ 65,  81,  34]],

       ...,

       [[ 97, 111,  78],
        [ 96, 107,  73],
        [ 99, 111,  75],
        ...,
        [ 25, 121,  24],
        [ 27, 127,  29],
        [ 22, 128,  30]],

       [[101, 112,  78],
        [ 97, 107,  72],
        [ 98, 108,  71],
        ...,
        [ 26, 128,  29],
        [ 21, 127,  29],
        [  9, 121,  21]],

       [[102, 112,  77],
        [ 95, 105,  68],
        [ 96, 104,  65],
        ...,
        [ 24, 128,  33],
        [ 19, 126,  32],
        [  6, 120,  24]]

In [17]:
car[0][0][0]

228

In [18]:
car[0][0][0:3]

array([228, 238, 247], dtype=uint8)